FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY shared/ ./shared/
COPY management-api/ ./management-api/
COPY go.mod go.sum ./

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /management-api ./management-api

FROM alpine:3.20

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /management-api /management-api

EXPOSE 8081

ENTRYPOINT ["/management-api"]
