FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY shared/ ./shared/
COPY worker/ ./worker/
COPY go.mod go.sum ./

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /worker ./worker

FROM alpine:3.20

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /worker /worker

ENTRYPOINT ["/worker"]
